import { AppProps } from 'next/app';
import '../styles/globals.css';
import Head from 'next/head';
import { Router } from 'next/router';

function MyApp({ Component, pageProps, router }: AppProps) {
  return(
  <>
	<Head>
		<title>Next App</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
		<meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}/>
		<meta property='og:locale' content="ru-RU"/>
		<meta property='og:type' content="article"/>
    </Head>
    <Component {...pageProps} />
    
  </>) ;
}

export default MyApp;
