import { AppProps } from 'next/app';
import '../styles/globals.css';
import Head from 'next/head';
import ym from 'react-yandex-metrika';
import { YMInitializer } from 'react-yandex-metrika';

function MyApp({ Component, pageProps, router }: AppProps) {
	router.events.on('routeChangeComplete', (url: string) => {
		if(typeof window !== 'undefined'){
			ym('hit', url);
		}
	});
  
  return(
  <>
	<Head>
		<title>Next App</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
		<link rel="preconnect" href="https://mc.yandex.ru" />
		<meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}/>
		<meta property='og:locale' content="ru-RU"/>
		<meta property='og:type' content="article"/>
    </Head>
    <YMInitializer accounts={[]} options={{webvisor: true, defer: true}} version='2'></YMInitializer>
    <Component {...pageProps} />
    
  </>) ;
}

export default MyApp;
